# Generated by Django 5.2.4 on 2025-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='energy',
            field=models.IntegerField(default=5),
        ),
    ]
