# Generated by Django 5.2.4 on 2025-09-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hinthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
