# Generated by Django 5.2.4 on 2025-09-16 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='energy',
            field=models.IntegerField(default=7),
        ),
    ]
